import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Background from "../../components/Background";
import Nav from "../../components/Navigation";
import Footer from "../../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Professional Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     <body className="min-h-full flex flex-col">
        <div className="relative min-h-screen w-full">
          <Nav />

          {/* Background page content */}
          {children}

          {/* Global draggable window  */}
          <Background />

          <Footer />
        </div>
      </body>
    </html>
  );
}