import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import Background from "../../components/Background";
import Nav from "../../components/Navigation";
import Footer from "../../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Professional Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className={`min-h-screen bg-[#06111b]
  bg-[radial-gradient(circle_at_top_left,_rgba(26,75,207,1),_transparent_30%)]
  bg-no-repeat bg-cover bg-fixed overflow-x-hidden
`}>

        <Nav />
        {/* Main content */}
        <main className="flex-grow">{children}</main>

        <Footer />

      </body>
    </html>
  );
}